# Generated by Django 4.2.4 on 2023-08-21 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Modality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient_id', models.CharField(max_length=100)),
                ('patient_name', models.CharField(max_length=100)),
                ('patient_sex', models.CharField(max_length=10)),
                ('referring_physicians_name', models.CharField(max_length=100)),
                ('requested_procedure_description', models.CharField(max_length=100)),
                ('study_instance_uid', models.CharField(max_length=100)),
                ('patient_birth_date', models.DateTimeField()),
                ('station_id', models.IntegerField()),
            ],
        ),
    ]
