# Generated by Django 4.2.4 on 2023-08-27 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Modality', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Study',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('study_instance_uid', models.CharField(max_length=100, unique=True)),
                ('patient_name', models.CharField(max_length=100)),
                ('patient_id', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series_instance_uid', models.CharField(max_length=100, unique=True)),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Modality.study')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dicom_path', models.FilePathField()),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Modality.series')),
            ],
        ),
    ]
