# Generated by Django 4.2.4 on 2023-08-29 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Modality', '0002_study_series_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PatientNo', models.CharField(blank=True, max_length=50, null=True)),
                ('PatientName', models.TextField(blank=True, max_length=225, null=True)),
                ('PatientID', models.CharField(blank=True, max_length=50, null=True)),
                ('PatientBirthDate', models.DateTimeField(auto_now=True)),
                ('PatientSex', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='image',
            name='series',
        ),
        migrations.DeleteModel(
            name='Modality',
        ),
        migrations.RemoveField(
            model_name='series',
            name='study',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.DeleteModel(
            name='Series',
        ),
        migrations.DeleteModel(
            name='Study',
        ),
    ]
