# Generated by Django 4.2.4 on 2023-08-29 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Modality', '0003_patient_remove_image_series_delete_modality_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_no', models.CharField(max_length=50)),
                ('file_data', models.CharField(max_length=50)),
                ('file_name', models.CharField(max_length=50)),
                ('file_size', models.CharField(max_length=50)),
                ('report_no', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, null=True, upload_to='')),
                ('image_no', models.CharField(max_length=50)),
                ('sop_instance_uid', models.CharField(max_length=50)),
                ('modality', models.CharField(max_length=15)),
                ('bodypart_examined', models.CharField(max_length=50)),
                ('instance_number', models.CharField(max_length=50)),
                ('content_datetime', models.DateTimeField(auto_now=True)),
                ('numberofwaveformchannel', models.CharField(max_length=50)),
                ('numberofwaveformsamples', models.CharField(max_length=50)),
                ('sampling_frequency', models.CharField(max_length=50)),
                ('waveformbitsallocated', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Study',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('study_no', models.CharField(max_length=50)),
                ('student_instance_uid', models.CharField(max_length=50)),
                ('accession_no', models.CharField(max_length=50)),
                ('study_descripton', models.TextField(blank=True, max_length=255, null=True)),
                ('study_datetime', models.DateTimeField(auto_now=True)),
                ('PatientNo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Modality.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series_no', models.CharField(max_length=50)),
                ('series_instance_uid', models.CharField(max_length=50)),
                ('series_number', models.CharField(max_length=50)),
                ('accession_no', models.CharField(max_length=50)),
                ('series_description', models.TextField(blank=True, max_length=255, null=True)),
                ('series_datetime', models.DateTimeField(auto_now=True)),
                ('study_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Modality.study')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_data', models.CharField(max_length=50)),
                ('report_size', models.CharField(max_length=50)),
                ('reportno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Modality.file')),
            ],
        ),
        migrations.CreateModel(
            name='ModalitySystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Modality.file')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Modality.image')),
                ('report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Modality.report')),
                ('series', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Modality.series')),
                ('study', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Modality.study')),
            ],
        ),
        migrations.AddField(
            model_name='image',
            name='series',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Modality.series'),
        ),
        migrations.AddField(
            model_name='file',
            name='imageno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Modality.image'),
        ),
    ]
