# Generated by Django 4.2.4 on 2023-08-29 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Modality', '0004_file_image_study_series_report_modalitysystem_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='study',
            old_name='student_instance_uid',
            new_name='study_instance_uid',
        ),
    ]
