# Generated by Django 4.2.4 on 2023-08-30 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Modality', '0006_alter_file_file_data_alter_file_file_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='bodypart_examined',
            new_name='patient_orientation',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='image_no',
            new_name='photometric_interpretation',
        ),
        migrations.RenameField(
            model_name='study',
            old_name='study_descripton',
            new_name='study_description',
        ),
        migrations.RemoveField(
            model_name='image',
            name='numberofwaveformchannel',
        ),
        migrations.RemoveField(
            model_name='image',
            name='numberofwaveformsamples',
        ),
        migrations.RemoveField(
            model_name='image',
            name='sampling_frequency',
        ),
        migrations.RemoveField(
            model_name='image',
            name='waveformbitsallocated',
        ),
        migrations.AddField(
            model_name='image',
            name='bits_allocated',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='bits_stored',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='columns',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='high_bit',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='pixel_representation',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='rows',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='samples_per_pixel',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='content_datetime',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='study',
            name='PatientNo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Modality.patient'),
        ),
    ]
